name: ruby-ci
on:
  push:
    branch: main
jobs:
  test:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        ruby-version: ['2.2', '2.7', '3.2']

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: setup
        run: bundle install
      - name: test
        run: bundle exec rspec --format d
